export const TOKEN_EXPIRED = 'TOKEN_EXPIRED'
export const INVALID_TOKEN = 'INVALID_TOKEN'
export const INVALID_REFRESH_TOKEN = 'INVALID REFRESH TOKEN'
export const INVALID_USER_REFRESH_TOKEN = 'INVALID USER REFRESH TOKEN'
